package com.gala.tvapi.vrs.core;

import com.gala.tvapi.TVApiConfig;

public final class a extends TVApiConfig {
    public static final String A = (h + "ckLiveN.action?qpid=%s&cid=afbe8fd3d73448c9&ut=%s&uuid=%s&uid=%s&play_v=%s&platform=%s&version=1.0&v=%s&filename=%s&qd_uid=%s&qd_vip=%s&qd_vipres=%s&qd_src=%s&qd_tm=%s&qd_ip=%s&qd_sc=%s&qd_tvid=%s&qd_scc=%s&P00001=%s");
    public static final String B = (n + "setrc.action?terminalId=52&auth=%s&tvId=%s&videoPlayTime=%s&agent_type=28");
    public static final String C = (n + "getrc.action?terminalId=52&auth=%s&limit=%s&dp=1&vp=%s&only_long=%s&agent_type=28");
    public static final String D = (n + "delrc.action?terminalId=52&auth=%s&empty=1&agent_type=28");
    public static final String E = (n + "getallrc.action?terminalId=52&dp=1&auth=%s&pageNum=%s&pageSize=%s&vp=%s&only_long=%s&agent_type=28");
    public static final String F = (n + "getdetail?terminalId=52&auth=%s&tvId=%s&com=1&agent_type=28");
    public static final String G = (n + "getalbumrc?terminalId=52&auth=%s&albumId=%s&com=1&agent_type=28");
    public static final String H = (n + "delrc.action?terminalId=52&auth=%s&tvId=%s&agent_type=28");
    public static final String I = (n + "getUpdateReminder?terminalId=52&auth=%s&number=%s&agent_type=28");
    public static final String J = (m + "setrc.action?terminalId=52&ckuid=%s&tvId=%s&videoPlayTime=%s&agent_type=28");
    public static final String K = (m + "getrc.action?terminalId=52&dp=1&ckuid=%s&limit=%s&vp=%s&only_long=%s&agent_type=28");
    public static final String L = (m + "delrc.action?terminalId=52&ckuid=%s&empty=1&agent_type=28");
    public static final String M = (m + "getdetail?terminalId=52&ckuid=%s&tvId=%s&com=1&agent_type=28");
    public static final String N = (m + "getalbumrc?terminalId=52&ckuid=%s&albumId=%s&com=1&agent_type=28");
    public static final String O = (m + "getUpdateReminder?terminalId=52&ckuid=%s&number=%s&agent_type=28");
    public static final String P = (n + "merge.action?terminalId=52&auth=%s&ckuid=%s&agent_type=28");
    public static final String Q = (n + "getalbumrcs?terminalId=52&albumIds=%s&auth=%s&agent_type=28");
    public static final String R = (m + "getalbumrcs?terminalId=52&albumIds=%s&ckuid=%s&agent_type=28");
    public static final String S = (m + "delrc.action?terminalId=52&ckuid=%s&tvId=%s&com=1&agent_type=28");
    public static final String T = (l + "watchlater/list.action?authcookie=%s&page=%s&pageSize=%s&all=0&agent_type=28&containsUgc=0&copyright=4&subTypes=%s");
    public static final String U = (l + "watchlater/deleteAllSubscriptions.action?authcookie=%s&antiCsrf=%s&agent_type=28");
    public static final String V = (k + "subscribe.action?subType=%s&subKey=%s&authcookie=%s&channelId=%s&antiCsrf=%s&agent_type=28");
    public static final String W = (k + "unsubscribe.action?subType=%s&subKey=%s&authcookie=%s&channelId=%s&antiCsrf=%s&agent_type=28");
    public static final String X = (k + "isSubscribed.action?subType=%s&subKey=%s&authcookie=%s&channelId=%s&agent_type=28");
    public static final String Y = (VRS_CACHE_SERVER + "cs/?m=%s&src=04022001010000000000");
    public static final String Z = (VRS_RECOMMEND_SERVER + "itv/ichannel/%s/?m=%s&src=04022001010000000000");
    public static final String aA = (q + "weather/weather?location=%s");
    public static final String aB = (r + "papaq-api/home/videos/%s?cursor=%s");
    public static final String aC = (o + "user/device/reg.action?deviceId=%s&deviceName=%s&logoUrl=%s&extraInfo=%s&sign=%s");
    public static final String aD = (o + "user/device/device_info.action?deviceId=%s&deviceSid=%s&sign=%s");
    public static final String aE = (o + "user/device/bind.action?authcookie=%s&deviceId=%s&deviceSid=%s&agentType=86&relationType=0&deviceNickName=%s&sign=%s");
    public static final String aF = (o + "user/device/unbind_device.action?authcookie=%s&deviceId=%s&agentType=86&sign=%s");
    public static final String aG = (o + "user/device/unbind_user.action?deviceId=%s&uid=%s&agentType=28&sign=%s");
    public static final String aH = (o + "user/device/update_device_nick_name.action?authcookie=%s&deviceId=%s&agentType=86&deviceNickName=%s&sign=%s");
    public static final String aI = (o + "user/device/my_devices.action?authcookie=%s&agentType=86&relationType=0&status=%s&sign=%s");
    public static final String aJ = (o + "user/device/send_ugc_message.action?authcookie=%s&type=%s&files=%s&device_id=%s&app_id=%s&app_ver=%s&agenttype=86&platform_type=21&msg_type=%s&duration=%s&msg_title=%s&msg_content=%s&msg_url=%s&msg_alert_body=%s&priority=0&expire=%s&qichuanIds=%s&sign=%s");
    public static final String aK = (p + "push/message/push_to_me.action?authcookie=%s&device_ids=%s&app_id=%s&app_ver=%s&agenttype=86&platform_type=21&msg_type=%s&duration=%s&msg_title=%s&msg_content=%s&msg_url=%s&msg_alert_body=%s&priority=0&device_policy=%s&qpid=%s&sourceid=%s&sign=%s");
    public static final String aL = (s + "movie_p13n/set_init?area=t_fox&ppuid=%s&uid=%s&entity_ids=%s");
    public static final String aM = (VRS_RECOMMEND_SERVER + "recommend/themes/videos?area=t_fox&userId=%s&cookieId=%s&themeSize=%s&forceInit=%s&version=%s&deviceId=%s&src=04022001010000000000");
    public static final String aN = (VRS_RECOMMEND_SERVER + "mixin/videos?tvIds=%s&version=%s&deviceId=%s&src=04022001010000000000");
    public static final String aO = (o + "cmonitor/keepalive_interval.action?authcookie=%s");
    public static final String aP = (o + "cmonitor/keepalive.action?authcookie=%s&agenttype=%s&device_id=%s&tv_id=%s&sign=%s");
    public static final String aQ = (o + "user/secure_check_vip.action?authcookie=%s&agenttype=%s&sign=%s&device_id=%s&ptid=04022001010000000000");
    public static final String aR = (t + "beaver-api/external/add_movie_score?qipu_id=%s&authcookie=%s&udid=%s&score=%s&appid=73");
    public static final String aS = (t + "beaver-api/external/get_user_movie_score?qipu_id=%s&uid=%s&udid=%s&appid=73");
    public static final String aT = (VRS_RECOMMEND_SERVER + "vms?key=ichannel&src=04022001010000000000&m=%s&isFree=%s&version=%s&apkVersion=%s");
    public static final String aU = (o + "qrcode/gen_login_token.action?agenttype=28&device_name=%s&device_id=%s");
    public static final String aV = (o + "qrcode/is_token_login.action?agenttype=28&token=%s&device_id=%s&fields=userinfo,vip_info,tv_vip_info,insecure_account");
    public static final String aW = (o + "qrcode/token_login_confirm.action?agenttype=86&token=%s&authcookie=%s&device_id=%s");
    public static final String aX = (o + "qrcode/opt/gen_login_token.action?agenttype=28&device_name=%s&authcookie=%s&device_id=%s");
    public static final String aY = (o + "qrcode/opt/is_login_requested.action?agenttype=28&token=%s&authcookie=%s&device_id=%s");
    public static final String aZ = (o + "qrcode/opt/is_login_confirmed.action?agenttype=86&token=%s&device_id=%s");
    public static final String aa = (w + "itv/plst/%s/7/?isFree=%s&apkVersion=%s&m=%s&src=04022001010000000000");
    public static final String ab = (w + "itv/plst/%s/7/%s/%s/?isFree=%s&apkVersion=%s&m=%s&src=04022001010000000000");
    public static final String ac = (VRS_RECOMMEND_SERVER + "recommend/videos?userId=%s&cookieId=%s&size=%s&channelId=%s&type=user&area=%s&isFree=%s&version=%s&deviceId=%s&entitySource=ppc&purchaseTypes=0,1,2&src=04022001010000000000&playPlatform=TV_GALA");
    public static final String ad = (VRS_RECOMMEND_SERVER + "recommend/videos?page=%s&size=%s&type=video&referenceId=%s&albumId=%s&withRefer=false&area=%s&channelId=%s&isFree=%s&version=%s&deviceId=%s&entitySource=ppc&src=04022001010000000000&playPlatform=TV_GALA");
    public static final String ae = (VRS_RECOMMEND_SERVER + "recommend/videos?page=%s&size=%s&type=pop&channelId=%s&tagSet=%s&area=t_cat&withRefer=true&isFree=%s&version=%s&deviceId=%s&entitySource=ppc&src=04022001010000000000");
    public static final String af = (VRS_RECOMMEND_SERVER + "config/tv/pop?src=04022001010000000000");
    public static final String ag = (VRS_CACHE_SERVER + "liven/%s?lp=%s&src=04022001010000000000&pf=9&m=%s");
    public static final String ah = (v + "nl/%s/%s/%s/%s?lp=%s&src=04022001010000000000&pf=9&m=%s");
    public static final String ai = (VRS_CACHE_SERVER + "pc/pr/%s/?src=04022001010000000000");
    public static final String aj = (VRS_CACHE_SERVER + "pc/%s/?src=04022001010000000000");
    public static final String ak = (w + "itv/ichannel/3/%s/?isFree=%s&apkVersion=%s&m=%s&src=04022001010000000000");
    public static final String al = (w + "itv/ichannel/3/%s/%s/?isFree=%s&apkVersion=%s&m=%s&src=04022001010000000000");
    public static final String am = (w + "itv/ichannel/3/%s/?isFree=%s&version=%s&apkVersion=%s&m=%s&src=04022001010000000000");
    public static final String an = (w + "itv/ichannel/3/%s/?isFree=%s&version=%s&size=%s&apkVersion=%s&m=%s&src=04022001010000000000");
    public static final String ao = (VRS_CACHE_SERVER + "pls/%s/%s/%s/4/?m=%s&src=04022001010000000000");
    public static final String ap = (w + "itv/ichannel/3/%s/?isFree=%s&version=%s&interval=%s&apkVersion=%s&m=%s&src=04022001010000000000");
    public static final String aq = (e + "contentBuy.action?cid=afbe8fd3d73448c9&aid=%s&platform=890dbe91fbadca03&version=1.0&P00001=%s&lang=zh_CN");
    public static final String ar = (d + "v.f4v");
    public static final String as = (k + "subscribe.action?subType=%s&subKey=%s&ckuid=%s&channelId=%s&antiCsrf=%s&agent_type=28");
    public static final String at = (k + "unsubscribe.action?subType=%s&subKey=%s&ckuid=%s&channelId=%s&antiCsrf=%s&agent_type=28");
    public static final String au = (k + "isSubscribed.action?subType=%s&subKey=%s&ckuid=%s&channelId=%s&agent_type=28");
    public static final String av = (l + "uwl/merge?authcookie=%s&ckuid=%s&antiCsrf=%s&agent_type=28");
    public static final String aw = (l + "watchlater/list.action?ckuid=%s&page=%s&pageSize=%s&all=0&agent_type=28&containsUgc=0&copyright=4&subTypes=%s");
    public static final String ax = (l + "watchlater/deleteAllSubscriptions.action?ckuid=%s&antiCsrf=%s&agent_type=28");
    public static final String ay = (q + "weather/area/?");
    public static final String az = (q + "weather/location?ip=%s");
    public static String bA = (o + "partner/bf_login.action?macid=%s&agenttype=%s&qd_sc=%s&device_id=%s");
    public static String bB = (o + "partner/login.action?authcookie=%s&openid=%s&access_token=%s&agenttype=%s&type=1&need_unlogin_uid=0&account_type=%s&ott_version=%s&device_id=%s&platform_id=%s&qd_sc=%s");
    public static String bC = (o + "thirdparty/xm_sso.action?agenttype=%s&openid=%s&access_token=%s&device_id=%s");
    public static String bD = (VRS_CACHE_SERVER + "vi/%s/%s/?vt=%s&src=04022001010000000000");
    public static String bE = (f + "services/queryVodInfo.action?P00001=%s&status=0");
    public static String bF = (g + "client/store/qrcode/getIMG.action?crossLogin=1&width=%s&agentType=18&ptid=04022001010000000000&P00001=%s&src=509221_0&url=%s");
    public static String bG = (f + "services/use_vodcoupon.action?aid=%s&platform=ace05b55b5b4aa3c&P00001=%s&version=1.0");
    public static String bH = (VRS_RECOMMEND_SERVER + "lives/channels/5/3/%s?src=04022001010000000000&boss=%s&apkVersion=%s&m=%s");
    public static String bI = (VRS_RECOMMEND_SERVER + "lives/programs/channels/pagebreak/%s?src=04022001010000000000&days=%s&cids=%s&page=%s");
    public static String bJ = (VRS_RECOMMEND_SERVER + "lives/programs/channels/cur-next?cids=%s&src=04022001010000000000");
    public static final String bK = (w + "itv/groupdetail/%s/?tms=%s&isFree=%s&local=%s&apkVersion=%s&version=%s&m=%s&src=%s");
    public static final String bL = (w + "itv/groupdetail/%s/?tms=%s&pageNo=%s&isFree=%s&local=%s&apkVersion=%s&version=%s&m=%s&src=%s");
    public static final String bM = (VRS_RECOMMEND_SERVER + "mixin/videos/qipuId?id=%s");
    public static final String bN = (j + "services/subscribe/add.htm?authcookie=%s&subType=2&subKeys=%s&agentType=%s");
    public static final String bO = (j + "services/subscribe/cancel.htm?authcookie=%s&subType=2&subKeys=%s&agentType=%s");
    public static final String bP = (j + "services/subscribe/countAndState.htm?authcookie=%s&subType=2&subKeys=%s&agentType=%s");
    public static final String bQ = (j + "services/subscribe/tv/list.htm?authcookie=%s&page=%s&rows=%s&filmType=%s&sort=%s&agentType=%s");
    public static final String bR = (bU + "aid=%s&cid=afbe8fd3d73448c9&vid=%s&ut=%s&utt=%s&uuid=%s&platform=9cc15614cfdf23bd&version=1.0&v=%s&P00001=%s");
    public static final String bS = (f + "mobile/productRecommend.action?pid=9ff1a15abb9b50b8&aid=%s&version=3.0&platform=9cc15614cfdf23bd&P00001=%s");
    public static final String bT = (g + "pay/dopay.action?serviceCode=lyksc7aq36aedndk&platform=9cc15614cfdf23bd&pid=9ff1a15abb9b50b8&amount=%s&aid=%s&payType=%s&fr_version=%s&vd=%s&expCard=%s&P00001=%s&signType=%s");
    private static final String bU = (h + "ck.action?");
    public static final String ba = (o + "qrcode/opt/login_confirm.action?agenttype=28&token=%s&authcookie=%s&device_id=%s");
    public static final String bb = (o + "reglogin/renew_authcookie.action?authcookie=%s&dfp=%s&envinfo=%s&device_id=%s&agenttype=%s&ptid=%s");
    public static final String bc = (o + "user/authlogin.action?agenttype=28&authcookie=%s&mac=%s&hid=%s&device_id=%s");
    public static final String bd = (o + "user/info.action?agenttype=28&authcookie=%s&device_id=%s&fields=userinfo,vip_info,tv_vip_info,insecure_account&ptid=04022001010000000000");
    public static final String be = (o + "user/info.action?agenttype=%s&authcookie=%s&device_id=%s&fields=userinfo,vip_info,tv_vip_info,insecure_account&=04022001010000000000");
    public static final String bf = (f + "pay/exp_pay.action?expCard=%s&payType=6&vd=%s&cid=afbe8fd3d73448c9&version=1.1&platform=890dbe91fbadca03&P00001=%s");
    public static final String bg = (f + "pay/exp_pay.action?expCard=%s&payType=6&vd=%s&cid=afbe8fd3d73448c9&version=1.1&platform=bb6197e86749df25&P00001=%s&limitCode=%s");
    public static final String bh = (g + "api/expcard/verify.action?expCard=%s&P00001=%s&app_lm=%s&platform=%s&cid=afbe8fd3d73448c9&version=%s");
    public static final String bi = (f + "order/gvc.action?width=%s&height=%s&P00001=%s");
    public static final String bj = (o + "user/mobile/login.action?email=%s&passwd=%s&agenttype=%s&sign=%s&port=&mac=%s&imei=&hid=%s&device_id=%s&device_name=%s");
    public static final String bk = (o + "user/logout.action?authcookie=%s&agenttype=28&device_id=%s");
    public static final String bl = (o + "user/check_account.action?account=%s&agenttype=28&device_id=%s");
    public static final String bm = (o + "phone/send_cellphone_authcode.action?requestType=1&cellphoneNumber=%s&serviceId=5&agenttype=28&device_id=%s");
    public static final String bn = (o + "phone/send_cellphone_authcode_vcode.action?requestType=%s&cellphoneNumber=%s&serviceId=5&agenttype=28&vcode=%s&QC005=%s");
    public static final String bo = (o + "phone/secure_send_cellphone_authcode.action?requestType=%s&cellphoneNumber=%s&serviceId=%s&area_code=%s&agenttype=%s&QC005=%s&ptid=%s&vcode=%s&qd_sc=%s");
    public static final String bp = (o + "reglogin/cellphone_authcode_login.action?cellphoneNumber=%s&area_code=%s&requestType=%s&serviceId=%s&authCode=%s&ptid=%s&agenttype=%s&device_id=%s&qd_sc=%s");
    public static final String bq = (o + "phone/cellphone_reg.action?authCode=%s&cellphoneNumber=%s&password=%s&serviceId=5&agenttype=%s&port=&mac=%s&imei=&hid=%s&device_id=%s");
    public static final String br = (o + "user/mobile/sregister.action?email=%s&passwd=%s&agenttype=%s&sign=%s&QC005=%s&vcode=%s&port=&mac=%s&imei=%s&hid=%s&device_id=%s");
    public static final String bs = (o + "reglogin/tv_cellphone_reg.action?authCode=%s&cellphoneNumber=%s&password=%s&serviceId=5&agenttype=%s&port=&mac=%s&imei=&hid=%s");
    public static final String bt = (o + "register/vcode.action?height=%s&width=%s&static=0&agenttype=%s&QC005=%s&device_id=%s");
    public static final String bu = (o + "user/info.action?agenttype=28&authcookie=%s&fields=icon&device_id=%s");
    public static final String bv = (o + "thirdparty/save_auth_token.action?source=22&agenttype=28&ouid=%s&atoken=%s&atoken_secret=%s&expire=%s&ouname=%s&refresh_token=%s&gender=%s&icon=%s&device_id=%s");
    public static String bw = (f + "agent/tvQRCode.action?pid=%s&version=1.0&platform=890dbe91fbadca03&fc=%s&width=%s&ut=%s&sign=%s&TV_UUID=%s&P00001=%s");
    public static String bx = (o + "reglogin/tv_login.action?email=%s&passwd=%s&vcode=%s&agenttype=%s&QC005=%s&device_id=%s&device_name=%s&port=&mac=%s&imei=%s&hid=%s&fields=%s&ptid=04022001010000000000");
    public static String by = (o + "subaccount/login.action?macid=%s&device_name=%s&agenttype=%s&sign=%s&device_id=%s");
    public static String bz = (o + "thirdparty/third_sso.action?agenttype=%s&access_token=%s&type=%s&device_id=%s");
    public static final String x = (bU + "aid=%s&cid=afbe8fd3d73448c9&vid=%s&ut=%s&utt=%s&uuid=%s&platform=%s&version=1.0&v=%s&P00001=%s&deviceId=%s");
    public static final String y = (h + "ckLive.action?qpid=%s&cid=afbe8fd3d73448c9&ut=%s&uuid=%s&uid=%s&play_v=%s&platform=%s&version=1.0&v=%s&P00001=%s");
    public static final String z = (f + "mobile/productRecommend.action?pid=%s&version=%s&lang=zh_TW&app_lm=tw&platform=%s");

    static {
        new StringBuilder().append(VRS_CACHE_SERVER).append("a/%s?m=%s&src=04022001010000000000");
        new StringBuilder().append(VRS_CACHE_SERVER).append("avlist/%s/%s/?m=%s&src=04022001010000000000");
        new StringBuilder().append(c).append("%s/%s/?t=%s&sc=%s&uid=%s&src=%s&m=%s&nolimit=%s&deviceid=%s&agenttype=%s&k_ft1=%s&ptid=%s");
        new StringBuilder().append(c).append("%s/%s/?t=%s&sc=%s&uid=%s&src=%s&m=%s&nolimit=%s&deviceid=%s&agenttype=%s");
        new StringBuilder().append(VRS_CACHE_SERVER).append("sdvlst/%s/%s/?m=%s&src=04022001010000000000");
        new StringBuilder().append(VRS_CACHE_SERVER).append("sdvlst/%s/%s/%s/?m=%s&src=04022001010000000000");
        new StringBuilder().append(VRS_CACHE_SERVER).append("sdlst/%s/%s/?m=%s&src=04022001010000000000");
        new StringBuilder().append(i).append("up/videos/%s/%s/json/");
    }
}
