package com.gala.tvapi.tv2.model;

public class Cnf extends Model {
    private static final long serialVersionUID = 1;
    public String acrossCode = "";
    public String ad = "";
    public String ad_guide_become_vip_text = "";
    public String adinfo = "";
    public String backgroundUrl = "";
    public String bootUrl = "";
    public String bug_vip_tip_pic = "";
    public String buyVipContentPic = "";
    public String canntJumpAdvertising = "";
    public String carouselDefaultPic;
    public String carouselDefaultPicSmall;
    public String carouselloadinginfo = "";
    public String codeURL = "";
    public String ctime = "";
    public String dailyInforCornerMark = "";
    public String dailyInformation = "";
    public String dailyInformationId = "";
    public String dailyTags = "";
    public String dailyTagsId = "";
    public String dailyTagsId2 = "";
    public String defUrl = "";
    public String desc = "";
    public String detailExitDialogResId = "";
    public String detail_free_video_bg = "";
    public String detail_month_vip_bg = "";
    public String devErr = "";
    public String document = "";
    public String exit = "";
    public String exitAppImageUrl = "";
    public String faq = "";
    public String feedbackInfoTip = "";
    public String free = "";
    public String ftinfo = "";
    public String guide_4k_bottom_desc = "";
    public String guide_bg_1080p_url = "";
    public String guide_bg_4k_url = "";
    public String guide_bg_hdr_url = "";
    public String guide_hdr_bottom_desc = "";
    public String headLogoUrl = "";
    public String headUrl = "";
    public String home_header_vip_text = "";
    public String home_header_vip_url = "";
    public String iChn = "";
    public String informationUrl = "";
    public String iseUrl = "";
    public String iseeUrl = "";
    public String jstvList = "";
    public String jstvUrl = "";
    public String live_purchase_guide_tip_image = "";
    public String live_purchase_guide_tip_text = "";
    public String loginButtonBelowText;
    public String loginCode = "";
    public String loginPageLeftPicUrl;
    public String membership_purchase_guide_info;
    public String modifyPwdQRCode = "http://cms.ptqy.gitv.tv/common/tv/user/setting.html";
    public String mulCtr = "";
    public String mulVip = "";
    public String myAccountCloseTip = "";
    public String myAccountInfoPicUrl = "";
    public String name = "";
    public String ncinfo = "";
    public String onlyIsee = "";
    public String openAcc = "";
    public String operation_pic_resource_ids = "";
    public String other = "";
    public String packageCover = "";
    public String packageCoverUrl = "";
    public String phone = "";
    public String phoneTips = "支持Android,iPhone";
    public String pinfo = "";
    public String platCnt = "";
    public String playBgUrl = "";
    public String playLoading = "";
    public String playNewUrl = "";
    public String playUrl = "";
    public String playerBackColour = "";
    public String playerBackColourUrl = "";
    public String playerLogo = "";
    public String player_tip_collections = "";
    public String ppsList = "";
    public String ppsUrl = "";
    public String preOver = "";
    public String purchase_button_text = "";
    public String purchase_guide_tip_image = "";
    public String purchase_guide_tip_text = "";
    public String retry_times_after_started = "3";
    public String retry_times_berfore_started = "3";
    public String screenInteractive1 = "";
    public String screenInteractive2 = "";
    public String screenUrl = "";
    public String screenWeChatInteractive = "";
    public String servUrl = "";
    public String signin_login_pic_url = "";
    public String signin_login_text = "";
    public String startLoading = "";
    public String startUrl = "";
    public String todayInformation = "";
    public String utime = "";
    public String verErr;
    public String videoSourceUrl = "";
    public String vipBrief = "";
    public String vipHead = "";
    public String vipPushPreviewEndTip = "";
    public String vipPushPreviewTip = "";
    public String vipResourceId = "";
    public String waterUrl = "";

    public boolean isOpenAccount() {
        return this.openAcc.equals("1");
    }

    public boolean isOpenMultiScreen() {
        return this.mulCtr.equals("1");
    }
}
